---
title: "TP4"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Question 2 : Chargemetn des donn?es
```{r}
D<- read.table("breast-cancer-wisconsin.data",sep=",",na.strings = "?")
```


Question 3

```{r}
class(D) 
str(D) 
head(D) 
summary(D)
```


3. SEPARATION DES DONNEES EN "TRAIN"  ET "TEST"

Question 4
```{r}
missval<-which(complete.cases(D)==F)
print(missval)
print(length(missval))
```


Question 5 : 

```{r}
D<-D[which(complete.cases(D)),]
```


Question 6 : 

```{r}
X<-D[,c(2:10)]
y<-D[,11]
```


Question 7 : 
```{r}
library(dplyr)
y<-recode(y, '2' = 0 , '4' = 1)
```


Question 8 : 
```{r}
benin<-which(y==0)
malin<-which(y==1)
```


Question 9 :
```{r}

train_set <- head(benin,200)
Xtrain <- X[train_set,]
ytrain<- y[train_set]


test_set <- c(benin[201:444],malin)

Xtest <- X[test_set,]
ytest <-y[test_set]

```



---------------------------------------------- KERNEL SVM -----------------------------------------------------

Question 10

```{r}
library(e1071)
```


Question 11
```{r}
oc_svm_fit <- svm(Xtrain,ytrain,type='one-classification', gamma=1/2)

```

```{r}
oc_svm_pred_test <- predict(oc_svm_fit,Xtest,decision.values = TRUE)
```


```{r}
attr(oc_svm_pred_test," decision.values ")
oc_svm_score_test = -as.numeric(attr(oc_svm_pred_test,"decision.values"))
```

---------------------------------------------- KERNEL Courbe ROC -----------------------------------------------------



```{r}
library(ROCR)
```

```{r}
pred_oc_svm = prediction(oc_svm_score_test, y[test_set])
oc_svm_roc = performance(pred_oc_svm , measure = "tpr" , x.measure= "fpr")
plot(oc_svm_roc)

```

