---
title: "TP4"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Question 2 : Chargemetn des donn?es
```{r}
D<- read.table("breast-cancer-wisconsin.data",sep=",",na.strings = "?")
```

 
Question 3

```{r}
class(D) 
str(D) 
head(D) 
summary(D)
```


3. SEPARATION DES DONNEES EN "TRAIN"  ET "TEST"

Question 4
```{r}
missval<-which(complete.cases(D)==F)
print(missval)
print(length(missval))
```


Question 5 : 

```{r}
D<-D[which(complete.cases(D)),]
```


Question 6 : 

```{r}
X<-D[,c(2:10)]
y<-D[,11]
```


Question 7 : 
```{r}
library(dplyr)
y<-recode(y, '2' = 0 , '4' = 1)
```


Question 8 : 
```{r}
benin<-which(y==0)
malin<-which(y==1)
```


Question 9 :
```{r}

train_set <- head(benin,200)
Xtrain <- X[train_set,]
ytrain<- y[train_set]

test_set <- c(benin[201:444],malin)

Xtest <- X[test_set,]
ytest <-y[test_set]

```



---------------------------------------------- KERNEL PCA -----------------------------------------------------

Question 17 

```{r}

library(kernlab)
kernel=rbfdot(sigma=1/8) 
kernel

```

```{r}
mat_trainset<-as.matrix(X[train_set ,])
Ktrain=kernelMatrix(kernel ,x= mat_trainset)
```

```{r}
n<- nrow(Ktrain )  #pas sur
```


Question 18 
```{r}

k2=apply(Ktrain,1,sum) 
k3=apply(Ktrain ,2,sum) 
k4=sum(Ktrain) 
KtrainCent=matrix(0,ncol=n,nrow=n) 
for (i in 1:n)
{
  for (j in 1:n) {
    KtrainCent[i,j]=Ktrain[i,j]-1/n*k2[i]-1/n*k3[j]+1/n^2*k4 
  }
}
```




Question 19 
```{r}
eigen_KtrainCent<-eigen(KtrainCent)
```




Question 20
```{r}
s<-80
A=eigen_KtrainCent$vectors[,1:s]%*%diag(1/sqrt( eigen_KtrainCent$values[1:s]))
```




Question 21
```{r}
matX<-as.matrix(X)
K=kernelMatrix(kernel ,matX)
```


Question 22

```{r}
p1 <-( K )
p2 <-apply(K[,train_set] ,1 , sum )
#p3 <- sum(Ktrain)
p3 <- sum(K[train_set,train_set])
```


```{r}
ps<-NULL
```


```{r}

#n<-683
n<-200

#z<-201
i<-1
#for ( i in 1: n2 )
for (z in test_set )
{
  
  ps[i]= p1[z,z] -(2/n) * p2[z] + (1/n^2)* p3
  #z<-z+1
  i<-i+1
}
```




question 24
```{r}
#f1<-p2  #a verif 

#f1<- p1
f1<-K[test_set,train_set]
f2<-p2[train_set]
f3<-p2[test_set]
#f4 <- k4
f4<-p3
```

fmz --> mat 483*80 

```{r}


n2<-length(ytest)  #pas sur
n<-200
fl<-matrix(0,ncol=s,nrow=n2)
for (m in 1:s){
 #z<-201
  i<-0
  for (z in test_set ){
    i<-i+1
    temp<-0
    for (i2 in 1:n){
    
     temp <- temp +(A[i2,m]*( f1[i,i2] - (1/n)*f2[i2] - (1/n)*f3[i] + (1/n^2)*f4))
    }
    fl[i,m]<-temp
      #apply(A[,m],2,sum)*(sum(f1)-(1/n)*sum(f2)-(1/n))
    #z<-z+1
  }

}

```




QUestion 26 

```{r}
kpca_score_test <- ps - apply(fl^2,1,sum)
```



```{r}
kpca_score_test
```

Courbe roc 

```{r}
dfroc<-as.data.frame(cbind(ytest,kpca_score_test))
head(dfroc)
```

```{r}
dfroc2<-dfroc[order(kpca_score_test,decreasing = T),]
head(dfroc2)
tail(dfroc2)
```

```{r}
pred_oc_svm = prediction(oc_svm_score_test, y[test_set])
oc_svm_roc = performance(pred_oc_svm , measure = "tpr" , x.measure= "fpr")
plot(oc_svm_roc,col="red" )

pred_oc_acp=prediction(kpca_score_test ,ytest)
oc_svm_acp = performance(pred_oc_acp, measure = "tpr", x.measure
= "fpr")
plot(oc_svm_acp, add=T)

```


```{r}

z<- performance(pred_oc_svm , measure = "auc" )
z@y.values

z2<-performance(pred_oc_acp, measure = "auc")
z2@y.values

```

```{r}

plot(oc_svm_acp)
```

